# Generated by Django 3.2.12 on 2022-08-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recepcionista',
            field=models.BooleanField(default=False, verbose_name='Is recepcionista'),
        ),
    ]
