# Generated by Django 4.1.2 on 2022-10-24 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220906_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=100)),
                ('fielkey', models.FileField(upload_to='fielkey/')),
                ('fielcer', models.FileField(upload_to='fielcer/')),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='documento',
            name='fechaven',
            field=models.DateField(default=datetime.date(2022, 11, 8)),
        ),
    ]
