# Generated by Django 4.1.2 on 2022-10-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_firma_alter_documento_fechaven'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=100)),
                ('Contrasena', models.FileField(upload_to='Contraseña/')),
            ],
        ),
    ]
