# Generated by Django 4.1.2 on 2022-10-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_documento_expediente_alter_documento_fechaven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='expediente',
            field=models.CharField(max_length=100),
        ),
    ]
