# Generated by Django 4.1.2 on 2022-11-04 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_documento_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrasena',
            name='RFC',
            field=models.CharField(default=datetime.date(2022, 11, 19), max_length=100),
        ),
        migrations.AddField(
            model_name='firma',
            name='RFC',
            field=models.CharField(default=datetime.date(2022, 11, 19), max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='comentarios',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fechaven',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
    ]
