# Generated by Django 4.1.2 on 2022-11-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_contrasena_rfc_firma_rfc_alter_documento_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrasena',
            name='RFC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='firma',
            name='RFC',
            field=models.CharField(max_length=100),
        ),
    ]
